# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller
    - robotiq_gripper_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - lbr_A1
      - lbr_A2
      - lbr_A3
      - lbr_A4
      - lbr_A5
      - lbr_A6
      - lbr_A7
    action_ns: follow_joint_trajectory
    default: true

  robotiq_gripper_controller:
    type: GripperCommand
    joint: lbr_finger_joint
    action_ns: gripper_cmd